with opportunity as ( select * from {{ source('sfdc_aqb','opportunity') }}
), 
final 
as ( select  
 trim(id) as opportunity_id
,isdeleted as isdeleted
,trim(accountid) as accountid
,trim(recordtypeid) as recordtypeid
,isprivate as isprivate
,trim(name) as name
,trim(description) as description
,trim(stagename) as stagename
,amount as amount
,probability as probability
,expectedrevenue as expectedrevenue
,totalopportunityquantity as totalopportunityquantity
,closedate as closedate
,trim(type) as type
,trim(nextstep) as nextstep
,trim(leadsource) as leadsource
,isclosed as isclosed
,iswon as iswon
,trim(forecastcategory) as forecastcategory
,trim(forecastcategoryname) as forecastcategoryname
,trim(campaignid) as campaignid
,hasopportunitylineitem as hasopportunitylineitem
,trim(pricebook2id) as pricebook2id
,trim(ownerid) as ownerid
,createddate as createddate
,trim(createdbyid) as createdbyid
,lastmodifieddate as lastmodifieddate
,trim(lastmodifiedbyid) as lastmodifiedbyid
,systemmodstamp as systemmodstamp
,lastactivitydate as lastactivitydate
,fiscalquarter as fiscalquarter
,fiscalyear as fiscalyear
,trim(fiscal) as fiscal
,trim(contactid) as contactid
,lastvieweddate as lastvieweddate
,lastreferenceddate as lastreferenceddate
,trim(syncedquoteid) as syncedquoteid
,trim(contractid) as contractid
,hasopenactivity as hasopenactivity
,hasoverduetask as hasoverduetask
,trim(lastamountchangedhistoryid) as lastamountchangedhistoryid
,trim(lastclosedatechangedhistoryid) as lastclosedatechangedhistoryid
,budget_confirmed__c as budget_confirmed__c
,discovery_completed__c as discovery_completed__c
,roi_analysis_completed__c as roi_analysis_completed__c
,trim(aqb__accountrating__c) as aqb__accountrating__c
,trim(loss_reason__c) as loss_reason__c
,trim(aqb__alert__c) as aqb__alert__c
,aqb__anonymous__c as aqb__anonymous__c
,trim(aqb__campaignfund__c) as aqb__campaignfund__c
,trim(aqb__capacity__c) as aqb__capacity__c
,aqb__capitalgain__c as aqb__capitalgain__c
,aqb__charitablededuction__c as aqb__charitablededuction__c
,trim(aqb__comment__c) as aqb__comment__c
,aqb__costbasis__c as aqb__costbasis__c
,trim(aqb__currentstagetracklink__c) as aqb__currentstagetracklink__c
,aqb__dateproposalsubmitted__c as aqb__dateproposalsubmitted__c
,aqb__daysincurentstage__c as aqb__daysincurentstage__c
,aqb__deadline__c as aqb__deadline__c
,aqb__determinationdate__c as aqb__determinationdate__c
,aqb__donotcontact__c as aqb__donotcontact__c
,aqb__earlieststartdate__c as aqb__earlieststartdate__c
,trim(aqb__finishyear__c) as aqb__finishyear__c
,aqb__firstpaymentdate__c as aqb__firstpaymentdate__c
,aqb__fundingcomplete__c as aqb__fundingcomplete__c
,trim(aqb__fundraisingcampaign__c) as aqb__fundraisingcampaign__c
,aqb__giftamount__c as aqb__giftamount__c
,aqb__giftdate__c as aqb__giftdate__c
,trim(aqb__giftsubtype__c) as aqb__giftsubtype__c
,aqb__goalamount__c as aqb__goalamount__c
,trim(aqb__goalyear__c) as aqb__goalyear__c
,trim(aqb__goal_type__c) as aqb__goal_type__c
,aqb__irsdiscouintrate__c as aqb__irsdiscouintrate__c
,trim(aqb__includeinstageaverage__c) as aqb__includeinstageaverage__c
,aqb__initialnetpresentvalue__c as aqb__initialnetpresentvalue__c
,trim(aqb__institutionalunit__c) as aqb__institutionalunit__c
,trim(aqb__instrument__c) as aqb__instrument__c
,trim(aqb__kpichart1__c) as aqb__kpichart1__c
,trim(aqb__kpichart2__c) as aqb__kpichart2__c
,trim(aqb__kpichartsize__c) as aqb__kpichartsize__c
,aqb__lastactivityformula__c as aqb__lastactivityformula__c
,aqb__lateststartdate__c as aqb__lateststartdate__c
,aqb__marketvaluedate__c as aqb__marketvaluedate__c
,aqb__marketvalue__c as aqb__marketvalue__c
,aqb__maturitydate__c as aqb__maturitydate__c
,aqb__monthstopayment__c as aqb__monthstopayment__c
,aqb__nextactivitydate__c as aqb__nextactivitydate__c
,trim(aqb__nextactivity__c) as aqb__nextactivity__c
,trim(aqb__omi__c) as aqb__omi__c
,trim(aqb__opportunityexternalid__c) as aqb__opportunityexternalid__c
,aqb__opportunitymanagementindex__c as aqb__opportunitymanagementindex__c
,trim(aqb__ownerunit__c) as aqb__ownerunit__c
,trim(aqb__readiness__c) as aqb__readiness__c
,aqb__remainder__c as aqb__remainder__c
,aqb__revocable__c as aqb__revocable__c
,aqb__stagedate__c as aqb__stagedate__c
,trim(aqb__strategy__c) as aqb__strategy__c
,aqb__taxamount__c as aqb__taxamount__c
,aqb__totalassetamount__c as aqb__totalassetamount__c
,trim(aqcv_conversionid__c) as aqcv_conversionid__c
,total_funded_amount__c as total_funded_amount__c
,trim(aqc_businessplanprospect__c) as aqc_businessplanprospect__c
,trim(aqc_loss_reason__c) as aqc_loss_reason__c
,trim(vu_opportunity_owner_name__c) as vu_opportunity_owner_name__c
,trim(aqc_fiscal_year_top_propsect__c) as aqc_fiscal_year_top_propsect__c
,activity_report_identification__c as activity_report_identification__c
,activity_report_qualification__c as activity_report_qualification__c
,activity_report_verbal_proposal__c as activity_report_verbal_proposal__c
,trim(affinity_rating__c) as affinity_rating__c
,anticipated_ask_amount__c as anticipated_ask_amount__c
,anticipated_ask_date__c as anticipated_ask_date__c
,ask_amount__c as ask_amount__c
,ask_date__c as ask_date__c
,trim(closing_comments__c) as closing_comments__c
,trim(funding_type__c) as funding_type__c
,trim(reason__c) as reason__c
,research_needed__c as research_needed__c
,verbal_commitment__c as verbal_commitment__c
,trim(volunteer_indicator__c) as volunteer_indicator__c
,trim(aqb__fee1exception_aq__c) as aqb__fee1exception_aq__c
,trim(aqb__fee1exemptreason_aq__c) as aqb__fee1exemptreason_aq__c
,aqb__fee1exempt_aq__c as aqb__fee1exempt_aq__c
,trim(aqb__fee1sourceaccount_aq__c) as aqb__fee1sourceaccount_aq__c
,aqb__fee1_aq__c as aqb__fee1_aq__c
,trim(aqb__fee2exception_aq__c) as aqb__fee2exception_aq__c
,trim(aqb__fee2exemptreason_aq__c) as aqb__fee2exemptreason_aq__c
,aqb__fee2exempt_aq__c as aqb__fee2exempt_aq__c
,trim(aqb__fee2sourceaccount_aq__c) as aqb__fee2sourceaccount_aq__c
,aqb__fee2_aq__c as aqb__fee2_aq__c
,matillion_batch_id as matillion_batch_id
,matillion_updated_timestamp as matillion_updated_timestamp
,'sfdc_aqb'  as source_name 
  from opportunity
) 
select * from final 
