with contact as ( select * from {{ source('sfdc_aqb','contact') }}
), 
final 
as ( select  
 trim(id) as contact_id
,isdeleted as isdeleted
,trim(masterrecordid) as masterrecordid
,trim(accountid) as accountid
,trim(lastname) as lastname
,trim(firstname) as firstname
,trim(salutation) as salutation
,trim(middlename) as middlename
,trim(suffix) as suffix
,trim(name) as name
,trim(otherstreet) as otherstreet
,trim(othercity) as othercity
,trim(otherstate) as otherstate
,trim(otherpostalcode) as otherpostalcode
,trim(othercountry) as othercountry
,otherlatitude as otherlatitude
,otherlongitude as otherlongitude
,trim(othergeocodeaccuracy) as othergeocodeaccuracy
,trim(mailingstreet) as mailingstreet
,trim(mailingcity) as mailingcity
,trim(mailingstate) as mailingstate
,trim(mailingpostalcode) as mailingpostalcode
,trim(mailingcountry) as mailingcountry
,mailinglatitude as mailinglatitude
,mailinglongitude as mailinglongitude
,trim(mailinggeocodeaccuracy) as mailinggeocodeaccuracy
,trim(phone) as phone
,trim(fax) as fax
,trim(mobilephone) as mobilephone
,trim(homephone) as homephone
,trim(otherphone) as otherphone
,trim(assistantphone) as assistantphone
,trim(reportstoid) as reportstoid
,trim(email) as email
,trim(title) as title
,trim(department) as department
,trim(assistantname) as assistantname
,trim(leadsource) as leadsource
,birthdate as birthdate
,trim(description) as description
,trim(ownerid) as ownerid
,hasoptedoutofemail as hasoptedoutofemail
,hasoptedoutoffax as hasoptedoutoffax
,donotcall as donotcall
,createddate as createddate
,trim(createdbyid) as createdbyid
,lastmodifieddate as lastmodifieddate
,trim(lastmodifiedbyid) as lastmodifiedbyid
,systemmodstamp as systemmodstamp
,lastactivitydate as lastactivitydate
,lastcurequestdate as lastcurequestdate
,lastcuupdatedate as lastcuupdatedate
,lastvieweddate as lastvieweddate
,lastreferenceddate as lastreferenceddate
,trim(emailbouncedreason) as emailbouncedreason
,emailbounceddate as emailbounceddate
,isemailbounced as isemailbounced
,trim(photourl) as photourl
,trim(jigsaw) as jigsaw
,trim(jigsawcontactid) as jigsawcontactid
,trim(individualid) as individualid
,trim(aqb__anlink__c) as aqb__anlink__c
,trim(aqb__aname__c) as aqb__aname__c
,trim(aqb__accessibilitypreferences__c) as aqb__accessibilitypreferences__c
,trim(aqb__accountcapacity__c) as aqb__accountcapacity__c
,trim(aqb__accountmailingaddresstype__c) as aqb__accountmailingaddresstype__c
,trim(aqb__accountmailingaddress__c) as aqb__accountmailingaddress__c
,trim(aqb__accountmailingcity__c) as aqb__accountmailingcity__c
,trim(aqb__accountmailingcountry__c) as aqb__accountmailingcountry__c
,trim(aqb__accountmailingcounty__c) as aqb__accountmailingcounty__c
,trim(aqb__accountmailinglocality__c) as aqb__accountmailinglocality__c
,trim(aqb__accountmailingnote__c) as aqb__accountmailingnote__c
,trim(aqb__accountmailingpostalcode__c) as aqb__accountmailingpostalcode__c
,trim(aqb__accountmailingstate__c) as aqb__accountmailingstate__c
,trim(aqb__accountmailingstatus__c) as aqb__accountmailingstatus__c
,trim(aqb__accountmailingstreet__c) as aqb__accountmailingstreet__c
,trim(aqb__accountphone__c) as aqb__accountphone__c
,trim(aqb__accountreadiness__c) as aqb__accountreadiness__c
,trim(aqb__additionalinstitutionalsuffix__c) as aqb__additionalinstitutionalsuffix__c
,trim(aqb__addresschangeflags__c) as aqb__addresschangeflags__c
,trim(aqb__addressinusetext__c) as aqb__addressinusetext__c
,trim(aqb__addressinusetype__c) as aqb__addressinusetype__c
,aqb__age__c as aqb__age__c
,trim(aqb__alert__c) as aqb__alert__c
,trim(aqb__automatedalternatename__c) as aqb__automatedalternatename__c
,trim(aqb__automatedcommunityname__c) as aqb__automatedcommunityname__c
,trim(aqb__automateddefaultaddresssalutation__c) as aqb__automateddefaultaddresssalutation__c
,trim(aqb__automateddefaultgreetingsalutation__c) as aqb__automateddefaultgreetingsalutation__c
,trim(aqb__automatedformalname__c) as aqb__automatedformalname__c
,trim(aqb__automatedpreferredname__c) as aqb__automatedpreferredname__c
,aqb__awardgiftcredit__c as aqb__awardgiftcredit__c
,trim(aqb__businessaddresscity__c) as aqb__businessaddresscity__c
,trim(aqb__businessaddresscountry__c) as aqb__businessaddresscountry__c
,trim(aqb__businessaddresslocality__c) as aqb__businessaddresslocality__c
,trim(aqb__businessaddressnote__c) as aqb__businessaddressnote__c
,trim(aqb__businessaddresspostalcode__c) as aqb__businessaddresspostalcode__c
,trim(aqb__businessaddressstatepro__c) as aqb__businessaddressstatepro__c
,trim(aqb__businessaddressstatus__c) as aqb__businessaddressstatus__c
,trim(aqb__businessaddressstreet__c) as aqb__businessaddressstreet__c
,trim(aqb__businessaddresstype__c) as aqb__businessaddresstype__c
,trim(aqb__businessaddress__c) as aqb__businessaddress__c
,trim(aqb__businessemail__c) as aqb__businessemail__c
,trim(aqb__businessphone__c) as aqb__businessphone__c
,trim(aqb__caecategory__c) as aqb__caecategory__c
,trim(aqb__cnlink__c) as aqb__cnlink__c
,trim(aqb__cname__c) as aqb__cname__c
,trim(aqb__carrierroute__c) as aqb__carrierroute__c
,trim(aqb__causedeath__c) as aqb__causedeath__c
,trim(aqb__certifiedcityname__c) as aqb__certifiedcityname__c
,trim(aqb__certifiedstateabbreviation__c) as aqb__certifiedstateabbreviation__c
,trim(aqb__certifiedstreetname__c) as aqb__certifiedstreetname__c
,trim(aqb__certifiedzipcode__c) as aqb__certifiedzipcode__c
,trim(aqb__cityofdeath__c) as aqb__cityofdeath__c
,trim(aqb__comments__c) as aqb__comments__c
,trim(aqb__communitypassword__c) as aqb__communitypassword__c
,aqb__contactanonymousoption__c as aqb__contactanonymousoption__c
,aqb__contactcount__c as aqb__contactcount__c
,trim(aqb__contactexternalid__c) as aqb__contactexternalid__c
,trim(aqb__contactgrouping__c) as aqb__contactgrouping__c
,trim(aqb__contactmailingaddressstreetlineone__c) as aqb__contactmailingaddressstreetlineone__c
,trim(aqb__contactmailingaddressstreetlinethre__c) as aqb__contactmailingaddressstreetlinethre__c
,trim(aqb__contactmailingaddressstreetlinetwo__c) as aqb__contactmailingaddressstreetlinetwo__c
,trim(aqb__contactpicture__c) as aqb__contactpicture__c
,trim(aqb__contactsource__c) as aqb__contactsource__c
,trim(aqb__contact_mailing_address__c) as aqb__contact_mailing_address__c
,aqb__corroborateddeathdate__c as aqb__corroborateddeathdate__c
,trim(aqb__countryid__c) as aqb__countryid__c
,trim(aqb__countryofdeath__c) as aqb__countryofdeath__c
,trim(aqb__countynumber__c) as aqb__countynumber__c
,trim(aqb__county__c) as aqb__county__c
,aqb__dateobituaryattached__c as aqb__dateobituaryattached__c
,aqb__dateofdeathnotification__c as aqb__dateofdeathnotification__c
,trim(aqb__dateofdeathprecision__c) as aqb__dateofdeathprecision__c
,aqb__dateofdeath__c as aqb__dateofdeath__c
,trim(aqb__deathcorroboratedby__c) as aqb__deathcorroboratedby__c
,aqb__deceased__c as aqb__deceased__c
,trim(aqb__defaultaddresssal__c) as aqb__defaultaddresssal__c
,trim(aqb__defaultgreetingsal__c) as aqb__defaultgreetingsal__c
,trim(aqb__degreeyear__c) as aqb__degreeyear__c
,trim(aqb__degree_level__c) as aqb__degree_level__c
,trim(aqb__degree__c) as aqb__degree__c
,trim(aqb__deliverypoint1__c) as aqb__deliverypoint1__c
,trim(aqb__deliverypointcheckdigit__c) as aqb__deliverypointcheckdigit__c
,trim(aqb__deliverypointvalidationflag__c) as aqb__deliverypointvalidationflag__c
,trim(aqb__deliverypointvalidation__c) as aqb__deliverypointvalidation__c
,aqb__directoryincludesendemaillink__c as aqb__directoryincludesendemaillink__c
,aqb__directorypublishaddress__c as aqb__directorypublishaddress__c
,aqb__directorypublishcoredata__c as aqb__directorypublishcoredata__c
,aqb__directorypublisheducation__c as aqb__directorypublisheducation__c
,aqb__directorypublishemail__c as aqb__directorypublishemail__c
,aqb__directorypublishemployment__c as aqb__directorypublishemployment__c
,aqb__directorypublishinterests__c as aqb__directorypublishinterests__c
,aqb__directorypublishphone__c as aqb__directorypublishphone__c
,trim(aqb__districtalternate__c) as aqb__districtalternate__c
,aqb__districtisoverridden__c as aqb__districtisoverridden__c
,trim(aqb__district__c) as aqb__district__c
,aqb__donotarchive__c as aqb__donotarchive__c
,aqb__donotcontact__c as aqb__donotcontact__c
,aqb__donotsolicit__c as aqb__donotsolicit__c
,trim(aqb__educationlink__c) as aqb__educationlink__c
,trim(aqb__emailnotes__c) as aqb__emailnotes__c
,trim(aqb__emailpreference__c) as aqb__emailpreference__c
,trim(aqb__employername__c) as aqb__employername__c
,aqb__engagementscoreexperiential__c as aqb__engagementscoreexperiential__c
,aqb__engagementscorephilanthropic__c as aqb__engagementscorephilanthropic__c
,aqb__engagementscorevolunteer__c as aqb__engagementscorevolunteer__c
,aqb__engagmentscorecommunication__c as aqb__engagmentscorecommunication__c
,trim(aqb__ethnicity__c) as aqb__ethnicity__c
,trim(aqb__fipsstatecode__c) as aqb__fipsstatecode__c
,trim(aqb__fnlink__c) as aqb__fnlink__c
,trim(aqb__fname__c) as aqb__fname__c
,trim(aqb__flag__c) as aqb__flag__c
,trim(aqb__foodpreferences__c) as aqb__foodpreferences__c
,trim(aqb__full_name__c) as aqb__full_name__c
,trim(aqb__gender__c) as aqb__gender__c
,trim(aqb__greeting__c) as aqb__greeting__c
,trim(aqb__institution__c) as aqb__institution__c
,trim(aqb__institutionalarea1alternate__c) as aqb__institutionalarea1alternate__c
,aqb__institutionalarea1isoverridden__c as aqb__institutionalarea1isoverridden__c
,trim(aqb__institutionalarea1__c) as aqb__institutionalarea1__c
,trim(aqb__institutionalarea2alternate__c) as aqb__institutionalarea2alternate__c
,aqb__institutionalarea2isoverridden__c as aqb__institutionalarea2isoverridden__c
,trim(aqb__institutionalarea2__c) as aqb__institutionalarea2__c
,trim(aqb__institutionalarea3alternate__c) as aqb__institutionalarea3alternate__c
,aqb__institutionalarea3isoverridden__c as aqb__institutionalarea3isoverridden__c
,trim(aqb__institutionalarea3__c) as aqb__institutionalarea3__c
,trim(aqb__institutionalarea4alternate__c) as aqb__institutionalarea4alternate__c
,aqb__institutionalarea4isoverridden__c as aqb__institutionalarea4isoverridden__c
,trim(aqb__institutionalarea4__c) as aqb__institutionalarea4__c
,trim(aqb__institutionalsuffixoverride__c) as aqb__institutionalsuffixoverride__c
,trim(aqb__institutionalsuffix__c) as aqb__institutionalsuffix__c
,trim(aqb__internalcontactmailingstreetone__c) as aqb__internalcontactmailingstreetone__c
,trim(aqb__internalcontactmailingstreettwo__c) as aqb__internalcontactmailingstreettwo__c
,trim(aqb__involvementrating__c) as aqb__involvementrating__c
,aqb__involvementscore__c as aqb__involvementscore__c
,trim(aqb__isprimarycontact__c) as aqb__isprimarycontact__c
,trim(aqb__issecondarycontact__c) as aqb__issecondarycontact__c
,trim(aqb__languages__c) as aqb__languages__c
,aqb__lastactivitydate__c as aqb__lastactivitydate__c
,trim(aqb__latitude__c) as aqb__latitude__c
,trim(aqb__legacycontactidnumber__c) as aqb__legacycontactidnumber__c
,trim(aqb__linkedaddress__c) as aqb__linkedaddress__c
,trim(aqb__locationofdeath__c) as aqb__locationofdeath__c
,trim(aqb__longitude__c) as aqb__longitude__c
,trim(aqb__maidenname__c) as aqb__maidenname__c
,trim(aqb__mailingaddresstype__c) as aqb__mailingaddresstype__c
,trim(aqb__mailingdistrict__c) as aqb__mailingdistrict__c
,trim(aqb__mailinglists__c) as aqb__mailinglists__c
,trim(aqb__mailinglocality__c) as aqb__mailinglocality__c
,trim(aqb__mailingnote__c) as aqb__mailingnote__c
,trim(aqb__mailingregion__c) as aqb__mailingregion__c
,trim(aqb__mailingstatus__c) as aqb__mailingstatus__c
,trim(aqb__mailingstreetlinefour__c) as aqb__mailingstreetlinefour__c
,trim(aqb__mailingstreetlineone__c) as aqb__mailingstreetlineone__c
,trim(aqb__mailingstreetlinethree__c) as aqb__mailingstreetlinethree__c
,trim(aqb__mailingstreetlinetwo__c) as aqb__mailingstreetlinetwo__c
,trim(aqb__mailingtimezone__c) as aqb__mailingtimezone__c
,trim(aqb__maritalstatus__c) as aqb__maritalstatus__c
,trim(aqb__mobilework__c) as aqb__mobilework__c
,trim(aqb__mostrecenteventattendancelink__c) as aqb__mostrecenteventattendancelink__c
,trim(aqb__mostrecenteventattended__c) as aqb__mostrecenteventattended__c
,aqb__most_recent_event_attendance_date__c as aqb__most_recent_event_attendance_date__c
,aqb__most_recent_event_registration_date__c as aqb__most_recent_event_registration_date__c
,trim(aqb__most_recent_event_registration_link__c) as aqb__most_recent_event_registration_link__c
,trim(aqb__most_recent_event_registration__c) as aqb__most_recent_event_registration__c
,trim(aqb__name__c) as aqb__name__c
,aqb__nextactivitydate__c as aqb__nextactivitydate__c
,trim(aqb__nextactivity__c) as aqb__nextactivity__c
,trim(aqb__nickname__c) as aqb__nickname__c
,trim(aqb__notifiedby__c) as aqb__notifiedby__c
,aqb__number_of_events_attended__c as aqb__number_of_events_attended__c
,aqb__obituaryattached__c as aqb__obituaryattached__c
,trim(aqb__obituarylink__c) as aqb__obituarylink__c
,trim(aqb__otheremail__c) as aqb__otheremail__c
,trim(aqb__otherpreferences__c) as aqb__otherpreferences__c
,trim(aqb__ownerunit__c) as aqb__ownerunit__c
,trim(aqb__pnamelink__c) as aqb__pnamelink__c
,trim(aqb__pname__c) as aqb__pname__c
,trim(aqb__personalemail__c) as aqb__personalemail__c
,trim(aqb__phonenotes__c) as aqb__phonenotes__c
,trim(aqb__phonepreference__c) as aqb__phonepreference__c
,trim(aqb__placeofbirth__c) as aqb__placeofbirth__c
,trim(aqb__preferredyear__c) as aqb__preferredyear__c
,trim(aqb__presentation_preferences__c) as aqb__presentation_preferences__c
,trim(aqb__primaryemploymentlink__c) as aqb__primaryemploymentlink__c
,trim(aqb__primaryemploymenttitle__c) as aqb__primaryemploymenttitle__c
,aqb__primarygiftrecognitioncredit_percent__c as aqb__primarygiftrecognitioncredit_percent__c
,trim(aqb__pronoun__c) as aqb__pronoun__c
,trim(aqb__rfm__c) as aqb__rfm__c
,trim(aqb__regionalternate__c) as aqb__regionalternate__c
,aqb__regionisoverridden__c as aqb__regionisoverridden__c
,trim(aqb__region__c) as aqb__region__c
,trim(aqb__relationship__c) as aqb__relationship__c
,trim(aqb__residentialdeliveryindicator__c) as aqb__residentialdeliveryindicator__c
,trim(aqb__revertaddressinusetype__c) as aqb__revertaddressinusetype__c
,trim(aqb__salutationlink__c) as aqb__salutationlink__c
,trim(aqb__schoolemail__c) as aqb__schoolemail__c
,trim(aqb__school__c) as aqb__school__c
,aqb__secondarygiftrecognitioncreditpercent__c as aqb__secondarygiftrecognitioncreditpercent__c
,trim(aqb__secondarytype__c) as aqb__secondarytype__c
,trim(aqb__setup__c) as aqb__setup__c
,aqb__signator__c as aqb__signator__c
,trim(aqb__stateid__c) as aqb__stateid__c
,trim(aqb__stateprovinceofdeath__c) as aqb__stateprovinceofdeath__c
,trim(aqb__suffix__c) as aqb__suffix__c
,aqb__totalaccountopenopportunities__c as aqb__totalaccountopenopportunities__c
,aqb__totalengagementscore__c as aqb__totalengagementscore__c
,aqb__total_number_of_event_registrations__c as aqb__total_number_of_event_registrations__c
,aqb__total_of_all_registration_fees__c as aqb__total_of_all_registration_fees__c
,trim(aqb__type__c) as aqb__type__c
,aqb__useaccountaddressonimport__c as aqb__useaccountaddressonimport__c
,trim(aqb__vsealumnidegreecategory__c) as aqb__vsealumnidegreecategory__c
,aqb__validationdate__c as aqb__validationdate__c
,trim(aqb__verificationflag__c) as aqb__verificationflag__c
,trim(aqc_multipleethnicity__c) as aqc_multipleethnicity__c
,trim(aqcv_conversionid__c) as aqcv_conversionid__c
,trim(aqc_partial_birth_date__c) as aqc_partial_birth_date__c
,trim(aqb__engagementscorecategory__c) as aqb__engagementscorecategory__c
,aqb__engagementscoreoverride__c as aqb__engagementscoreoverride__c
,aqb__engagementscore__c as aqb__engagementscore__c
,trim(aqb__professionalsuffix__c) as aqb__professionalsuffix__c
,trim(aqc_contact_id_text__c) as aqc_contact_id_text__c
,aqc_power_of_one__c as aqc_power_of_one__c
,trim(vud_sort_name__c) as vud_sort_name__c
,trim(vud_contact_external_id__c) as vud_contact_external_id__c
,et4ae5__hasoptedoutofmobile__c as et4ae5__hasoptedoutofmobile__c
,trim(et4ae5__mobile_country_code__c) as et4ae5__mobile_country_code__c
,vu_account_total__c as vu_account_total__c
,trim(email_unsubscribe_reason__c) as email_unsubscribe_reason__c
,trim(aqb__dummytext_aq__c) as aqb__dummytext_aq__c
,trim(test_email_groups__c) as test_email_groups__c
,trim(id_full_characters__c) as id_full_characters__c
,matillion_batch_id as matillion_batch_id
,matillion_updated_timestamp as matillion_updated_timestamp
,'sfdc_aqb'  as source_name 
  from contact
) 
select * from final 
