with campaignmember as ( select * from {{ source('sfdc_aqb','campaignmember') }}
), 
final 
as ( select  
 trim(id) as campaignmember_id
,isdeleted as isdeleted
,trim(campaignid) as campaignid
,trim(leadid) as leadid
,trim(contactid) as contactid
,trim(accountid) as accountid
,trim(status) as status
,hasresponded as hasresponded
,createddate as createddate
,trim(createdbyid) as createdbyid
,lastmodifieddate as lastmodifieddate
,trim(lastmodifiedbyid) as lastmodifiedbyid
,systemmodstamp as systemmodstamp
,firstrespondeddate as firstrespondeddate
,trim(recordtypeid) as recordtypeid
,trim(salutation) as salutation
,trim(name) as name
,trim(firstname) as firstname
,trim(lastname) as lastname
,trim(title) as title
,trim(street) as street
,trim(city) as city
,trim(state) as state
,trim(postalcode) as postalcode
,trim(country) as country
,trim(email) as email
,trim(phone) as phone
,trim(fax) as fax
,trim(mobilephone) as mobilephone
,trim(description) as description
,donotcall as donotcall
,hasoptedoutofemail as hasoptedoutofemail
,hasoptedoutoffax as hasoptedoutoffax
,trim(leadsource) as leadsource
,trim(companyoraccount) as companyoraccount
,trim(type) as type
,trim(leadorcontactid) as leadorcontactid
,trim(leadorcontactownerid) as leadorcontactownerid
,trim(aqb__accountmember__c) as aqb__accountmember__c
,trim(aqb__account__c) as aqb__account__c
,aqb__active__c as aqb__active__c
,trim(aqb__address__c) as aqb__address__c
,aqb__affinaquestexternaladd__c as aqb__affinaquestexternaladd__c
,trim(aqb__alternatechannel__c) as aqb__alternatechannel__c
,trim(aqb__campaignrecordtypeid__c) as aqb__campaignrecordtypeid__c
,trim(aqb__city__c) as aqb__city__c
,trim(aqb__communicationaccount__c) as aqb__communicationaccount__c
,trim(aqb__communicationalternatechannel__c) as aqb__communicationalternatechannel__c
,trim(aqb__communicationcontact__c) as aqb__communicationcontact__c
,trim(aqb__communicationschannel__c) as aqb__communicationschannel__c
,trim(aqb__contact__c) as aqb__contact__c
,trim(aqb__country__c) as aqb__country__c
,aqb__delete__c as aqb__delete__c
,trim(aqb__email__c) as aqb__email__c
,trim(aqb__facebook__c) as aqb__facebook__c
,trim(aqb__firstgift__c) as aqb__firstgift__c
,aqb__firsttransactiondate__c as aqb__firsttransactiondate__c
,trim(aqb__firsttransaction__c) as aqb__firsttransaction__c
,trim(aqb__greeting__c) as aqb__greeting__c
,trim(aqb__instagram__c) as aqb__instagram__c
,trim(aqb__mailingname__c) as aqb__mailingname__c
,trim(aqb__ownerunit__c) as aqb__ownerunit__c
,trim(aqb__phonenumber__c) as aqb__phonenumber__c
,trim(aqb__postalcode__c) as aqb__postalcode__c
,trim(aqb__preferenceaccount__c) as aqb__preferenceaccount__c
,trim(aqb__preferencealternatechannel__c) as aqb__preferencealternatechannel__c
,trim(aqb__preferencecontact__c) as aqb__preferencecontact__c
,trim(aqb__preferredchannel__c) as aqb__preferredchannel__c
,trim(aqb__sms__c) as aqb__sms__c
,aqb__startdate__c as aqb__startdate__c
,trim(aqb__stateid__c) as aqb__stateid__c
,trim(aqb__stateprovince__c) as aqb__stateprovince__c
,aqb__stopdate__c as aqb__stopdate__c
,trim(aqb__streetlineone__c) as aqb__streetlineone__c
,trim(aqb__streetlinethree__c) as aqb__streetlinethree__c
,trim(aqb__streetlinetwo__c) as aqb__streetlinetwo__c
,trim(aqb__targetlisttype__c) as aqb__targetlisttype__c
,trim(aqb__targetlist_type__c) as aqb__targetlist_type__c
,trim(aqb__twitter__c) as aqb__twitter__c
,trim(aqcv_conversionid__c) as aqcv_conversionid__c
,trim(aqb__engagementscorecategory__c) as aqb__engagementscorecategory__c
,aqb__engagementscoreoverride__c as aqb__engagementscoreoverride__c
,aqb__engagementscore__c as aqb__engagementscore__c
,trim(et4ae5__activity__c) as et4ae5__activity__c
,trim(vu_fiscal_years_active__c) as vu_fiscal_years_active__c
,vu_most_recent_gift_date__c as vu_most_recent_gift_date__c
,matillion_batch_id as matillion_batch_id
,matillion_updated_timestamp as matillion_updated_timestamp
,'sfdc_aqb'  as source_name 
  from campaignmember
) 
select * from final 
