with aqb__aqaddress__c as ( select * from {{ source('sfdc_aqb','aqb__aqaddress__c') }}
), 
final 
as ( select  
 trim(id) as aqb__aqaddress__c_id
,trim(ownerid) as ownerid
,isdeleted as isdeleted
,trim(name) as name
,trim(recordtypeid) as recordtypeid
,createddate as createddate
,trim(createdbyid) as createdbyid
,lastmodifieddate as lastmodifieddate
,trim(lastmodifiedbyid) as lastmodifiedbyid
,systemmodstamp as systemmodstamp
,trim(aqb__accountexternalidlinkfield__c) as aqb__accountexternalidlinkfield__c
,trim(aqb__accountexternalid__c) as aqb__accountexternalid__c
,trim(aqb__accountprefaddlink__c) as aqb__accountprefaddlink__c
,trim(aqb__account__c) as aqb__account__c
,trim(aqb__addresschangeflags__c) as aqb__addresschangeflags__c
,trim(aqb__address__c) as aqb__address__c
,trim(aqb__carrierroute__c) as aqb__carrierroute__c
,trim(aqb__censustract__c) as aqb__censustract__c
,trim(aqb__certifiedcityname__c) as aqb__certifiedcityname__c
,trim(aqb__certifiedstateabbreviation__c) as aqb__certifiedstateabbreviation__c
,trim(aqb__certifiedstreetname__c) as aqb__certifiedstreetname__c
,trim(aqb__certifiedzipcode__c) as aqb__certifiedzipcode__c
,trim(aqb__changesource__c) as aqb__changesource__c
,trim(aqb__channeladdress__c) as aqb__channeladdress__c
,trim(aqb__city__c) as aqb__city__c
,trim(aqb__congressionaldistrict__c) as aqb__congressionaldistrict__c
,trim(aqb__contactexternalidlinkfield__c) as aqb__contactexternalidlinkfield__c
,trim(aqb__contactexternalid__c) as aqb__contactexternalid__c
,trim(aqb__contactprefaddlink__c) as aqb__contactprefaddlink__c
,trim(aqb__contact__c) as aqb__contact__c
,trim(aqb__countryid__c) as aqb__countryid__c
,trim(aqb__country__c) as aqb__country__c
,trim(aqb__countynumber__c) as aqb__countynumber__c
,trim(aqb__county__c) as aqb__county__c
,aqb__dpcheckdigit__c as aqb__dpcheckdigit__c
,trim(aqb__dpv__c) as aqb__dpv__c
,trim(aqb__deliverypoint1__c) as aqb__deliverypoint1__c
,trim(aqb__deliverypointcheckdigit__c) as aqb__deliverypointcheckdigit__c
,trim(aqb__deliverypointvalidationflag__c) as aqb__deliverypointvalidationflag__c
,trim(aqb__deliverypointvalidation__c) as aqb__deliverypointvalidation__c
,aqb__deliverypoint__c as aqb__deliverypoint__c
,trim(aqb__district__c) as aqb__district__c
,aqb__donotarchive__c as aqb__donotarchive__c
,trim(aqb__email__c) as aqb__email__c
,trim(aqb__employmentexternalid__c) as aqb__employmentexternalid__c
,trim(aqb__employmentlink__c) as aqb__employmentlink__c
,trim(aqb__fipsstatecode__c) as aqb__fipsstatecode__c
,trim(aqb__facebook__c) as aqb__facebook__c
,trim(aqb__fax__c) as aqb__fax__c
,aqb__first_use__c as aqb__first_use__c
,trim(aqb__flag__c) as aqb__flag__c
,trim(aqb__instagram__c) as aqb__instagram__c
,trim(aqb__internalstreetlineone__c) as aqb__internalstreetlineone__c
,trim(aqb__internalstreetlinetwo__c) as aqb__internalstreetlinetwo__c
,trim(aqb__internetaddress__c) as aqb__internetaddress__c
,trim(aqb__isactiveaddress__c) as aqb__isactiveaddress__c
,aqb__isactive__c as aqb__isactive__c
,trim(aqb__iscurrentactiveaddress__c) as aqb__iscurrentactiveaddress__c
,aqb__last_use__c as aqb__last_use__c
,trim(aqb__latitude__c) as aqb__latitude__c
,trim(aqb__linkedinurl__c) as aqb__linkedinurl__c
,trim(aqb__linkedto__c) as aqb__linkedto__c
,trim(aqb__locality__c) as aqb__locality__c
,trim(aqb__longitude__c) as aqb__longitude__c
,trim(aqb__mailinglists__c) as aqb__mailinglists__c
,trim(aqb__note__c) as aqb__note__c
,trim(aqb__origintype__c) as aqb__origintype__c
,trim(aqb__originalsource__c) as aqb__originalsource__c
,trim(aqb__ownerunit__c) as aqb__ownerunit__c
,trim(aqb__phone__c) as aqb__phone__c
,trim(aqb__postalcode__c) as aqb__postalcode__c
,trim(aqb__postcodecountry__c) as aqb__postcodecountry__c
,trim(aqb__postcodestateorprovince__c) as aqb__postcodestateorprovince__c
,aqb__prefaddrlinkerror__c as aqb__prefaddrlinkerror__c
,trim(aqb__preferredstartday__c) as aqb__preferredstartday__c
,trim(aqb__preferredstartmonth__c) as aqb__preferredstartmonth__c
,trim(aqb__region__c) as aqb__region__c
,trim(aqb__residentialdeliveryindicator__c) as aqb__residentialdeliveryindicator__c
,trim(aqb__sms__c) as aqb__sms__c
,trim(aqb__seasonalstartyear__c) as aqb__seasonalstartyear__c
,trim(aqb__seasonalstopdate__c) as aqb__seasonalstopdate__c
,trim(aqb__seasonalstopday__c) as aqb__seasonalstopday__c
,trim(aqb__seasonalstopmonth__c) as aqb__seasonalstopmonth__c
,trim(aqb__seasonalstopyear__c) as aqb__seasonalstopyear__c
,trim(aqb__skype__c) as aqb__skype__c
,trim(aqb__snapchat__c) as aqb__snapchat__c
,trim(aqb__source__c) as aqb__source__c
,trim(aqb__startdate__c) as aqb__startdate__c
,trim(aqb__stateid__c) as aqb__stateid__c
,trim(aqb__stateprovince__c) as aqb__stateprovince__c
,trim(aqb__status__c) as aqb__status__c
,trim(aqb__streetlinefour__c) as aqb__streetlinefour__c
,trim(aqb__streetlineone__c) as aqb__streetlineone__c
,trim(aqb__streetlineonex__c) as aqb__streetlineonex__c
,trim(aqb__streetlinethree__c) as aqb__streetlinethree__c
,trim(aqb__streetlinethreex__c) as aqb__streetlinethreex__c
,trim(aqb__streetlinetwo__c) as aqb__streetlinetwo__c
,trim(aqb__streetlinetwox__c) as aqb__streetlinetwox__c
,trim(aqb__street__c) as aqb__street__c
,trim(aqb__timezone__c) as aqb__timezone__c
,trim(aqb__twitch__c) as aqb__twitch__c
,trim(aqb__twitter__c) as aqb__twitter__c
,trim(aqb__type__c) as aqb__type__c
,aqb__unlisted__c as aqb__unlisted__c
,aqb__useasaccountmailingaddress__c as aqb__useasaccountmailingaddress__c
,aqb__useascontactbusinessaddress__c as aqb__useascontactbusinessaddress__c
,aqb__useascontactmailingaddress__c as aqb__useascontactmailingaddress__c
,trim(aqb__uses__c) as aqb__uses__c
,aqb__validationdate__c as aqb__validationdate__c
,aqb__verificationdate__c as aqb__verificationdate__c
,trim(aqb__verificationflag__c) as aqb__verificationflag__c
,trim(aqb__we_chat__c) as aqb__we_chat__c
,trim(aqb__youtubechannel__c) as aqb__youtubechannel__c
,trim(aqb__countryiso2__c) as aqb__countryiso2__c
,trim(aqb__countryiso3__c) as aqb__countryiso3__c
,trim(aqcv_conversionid__c) as aqcv_conversionid__c
,trim(aqb__primarychannellocation__c) as aqb__primarychannellocation__c
,matillion_batch_id as matillion_batch_id
,matillion_updated_timestamp as matillion_updated_timestamp
,'sfdc_aqb'  as source_name 
  from aqb__aqaddress__c
) 
select * from final 
