with aqb__batchitemtransaction__c as ( select * from {{ source('sfdc_aqb','aqb__batchitemtransaction__c') }}
), 
final 
as ( select  
 trim(id) as aqb__batchitemtransaction__c_id
,isdeleted as isdeleted
,trim(name) as name
,createddate as createddate
,trim(createdbyid) as createdbyid
,lastmodifieddate as lastmodifieddate
,trim(lastmodifiedbyid) as lastmodifiedbyid
,systemmodstamp as systemmodstamp
,trim(aqb__batchitemid__c) as aqb__batchitemid__c
,trim(aqb__acknowledgement__c) as aqb__acknowledgement__c
,aqb__amount__c as aqb__amount__c
,aqb__anonymous__c as aqb__anonymous__c
,trim(aqb__batchitemreferenceid__c) as aqb__batchitemreferenceid__c
,trim(aqb__campaignappeal__c) as aqb__campaignappeal__c
,trim(aqb__checknumber__c) as aqb__checknumber__c
,aqb__conditionalpledge__c as aqb__conditionalpledge__c
,aqb__correctingtransaction__c as aqb__correctingtransaction__c
,aqb__creditedyearoverridedate__c as aqb__creditedyearoverridedate__c
,aqb__currencyexchangerate__c as aqb__currencyexchangerate__c
,aqb__currencyunits__c as aqb__currencyunits__c
,aqb__dailyhigh__c as aqb__dailyhigh__c
,aqb__dailylow__c as aqb__dailylow__c
,aqb__datedue__c as aqb__datedue__c
,aqb__dateoftransfer__c as aqb__dateoftransfer__c
,aqb__date__c as aqb__date__c
,trim(aqb__description__c) as aqb__description__c
,trim(aqb__designation__c) as aqb__designation__c
,aqb__donotpushtoaccounting__c as aqb__donotpushtoaccounting__c
,trim(aqb__donorfacingdescription__c) as aqb__donorfacingdescription__c
,trim(aqb__fee1exception__c) as aqb__fee1exception__c
,trim(aqb__fee1exemptreason__c) as aqb__fee1exemptreason__c
,aqb__fee1exempt__c as aqb__fee1exempt__c
,trim(aqb__fee1sourceaccount__c) as aqb__fee1sourceaccount__c
,aqb__fee1__c as aqb__fee1__c
,trim(aqb__fee2exception__c) as aqb__fee2exception__c
,trim(aqb__fee2exemptreason__c) as aqb__fee2exemptreason__c
,aqb__fee2exempt__c as aqb__fee2exempt__c
,trim(aqb__fee2sourceaccount__c) as aqb__fee2sourceaccount__c
,aqb__fee2__c as aqb__fee2__c
,aqb__iradistribution__c as aqb__iradistribution__c
,trim(aqb__linktobatchitemtransaction__c) as aqb__linktobatchitemtransaction__c
,trim(aqb__linktoduespledge__c) as aqb__linktoduespledge__c
,trim(aqb__linktoduestransaction__c) as aqb__linktoduestransaction__c
,trim(aqb__linktoduestransactions__c) as aqb__linktoduestransactions__c
,trim(aqb__linktoopportunity__c) as aqb__linktoopportunity__c
,trim(aqb__linktopledge__c) as aqb__linktopledge__c
,trim(aqb__linktotransaction__c) as aqb__linktotransaction__c
,trim(aqb__method__c) as aqb__method__c
,aqb__numberofshares__c as aqb__numberofshares__c
,aqb__paymentnumber__c as aqb__paymentnumber__c
,aqb__pledgepayment__c as aqb__pledgepayment__c
,trim(aqb__pledgestipulation__c) as aqb__pledgestipulation__c
,trim(aqb__propertycategory__c) as aqb__propertycategory__c
,trim(aqb__recurringgiftexternalreferencenumber__c) as aqb__recurringgiftexternalreferencenumber__c
,trim(aqb__recurringgift__c) as aqb__recurringgift__c
,trim(aqb__reference__c) as aqb__reference__c
,aqb__sendpledgereminder__c as aqb__sendpledgereminder__c
,trim(aqb__solicitationcreditcontact__c) as aqb__solicitationcreditcontact__c
,trim(aqb__solicitationcredituser__c) as aqb__solicitationcredituser__c
,aqb__thirdpartypayment__c as aqb__thirdpartypayment__c
,aqb__thirdpartypayoff__c as aqb__thirdpartypayoff__c
,trim(aqb__tickersymbol__c) as aqb__tickersymbol__c
,trim(aqb__transaction_type__c) as aqb__transaction_type__c
,aqb__transfer__c as aqb__transfer__c
,aqb__void__c as aqb__void__c
,trim(aqb__voidnotation__c) as aqb__voidnotation__c
,trim(aqcv_conversionid__c) as aqcv_conversionid__c
,trim(aqb__account__c) as aqb__account__c
,trim(aqb__anonymitylevel__c) as aqb__anonymitylevel__c
,trim(aqb__linktonewgift__c) as aqb__linktonewgift__c
,aqb__linkedgift__c as aqb__linkedgift__c
,matillion_batch_id as matillion_batch_id
,matillion_updated_timestamp as matillion_updated_timestamp
,'sfdc_aqb'  as source_name 
  from aqb__batchitemtransaction__c
) 
select * from final 
