with campaign as ( select * from {{ source('sfdc_aqb','campaign') }}
), 
final 
as ( select  
 trim(id) as campaign_id
,isdeleted as isdeleted
,trim(name) as name
,trim(parentid) as parentid
,trim(type) as type
,trim(recordtypeid) as recordtypeid
,trim(status) as status
,startdate as startdate
,enddate as enddate
,expectedrevenue as expectedrevenue
,budgetedcost as budgetedcost
,actualcost as actualcost
,expectedresponse as expectedresponse
,numbersent as numbersent
,isactive as isactive
,trim(description) as description
,numberofleads as numberofleads
,numberofconvertedleads as numberofconvertedleads
,numberofcontacts as numberofcontacts
,numberofresponses as numberofresponses
,numberofopportunities as numberofopportunities
,numberofwonopportunities as numberofwonopportunities
,amountallopportunities as amountallopportunities
,amountwonopportunities as amountwonopportunities
,hierarchynumberofleads as hierarchynumberofleads
,hierarchynumberofconvertedleads as hierarchynumberofconvertedleads
,hierarchynumberofcontacts as hierarchynumberofcontacts
,hierarchynumberofresponses as hierarchynumberofresponses
,hierarchynumberofopportunities as hierarchynumberofopportunities
,hierarchynumberofwonopportunities as hierarchynumberofwonopportunities
,hierarchyamountallopportunities as hierarchyamountallopportunities
,hierarchyamountwonopportunities as hierarchyamountwonopportunities
,hierarchynumbersent as hierarchynumbersent
,hierarchyexpectedrevenue as hierarchyexpectedrevenue
,hierarchybudgetedcost as hierarchybudgetedcost
,hierarchyactualcost as hierarchyactualcost
,trim(ownerid) as ownerid
,createddate as createddate
,trim(createdbyid) as createdbyid
,lastmodifieddate as lastmodifieddate
,trim(lastmodifiedbyid) as lastmodifiedbyid
,systemmodstamp as systemmodstamp
,lastactivitydate as lastactivitydate
,lastvieweddate as lastvieweddate
,lastreferenceddate as lastreferenceddate
,trim(campaignmemberrecordtypeid) as campaignmemberrecordtypeid
,aqb__accountssolicited__c as aqb__accountssolicited__c
,trim(aqb__alert__c) as aqb__alert__c
,aqb__campaignappealbudget__c as aqb__campaignappealbudget__c
,trim(aqb__campaignexternalid__c) as aqb__campaignexternalid__c
,trim(aqb__campaignfund__c) as aqb__campaignfund__c
,aqb__daysinprogress__c as aqb__daysinprogress__c
,trim(aqb__defaultdesignation__c) as aqb__defaultdesignation__c
,aqb__donor_goal__c as aqb__donor_goal__c
,aqb__estimatedaccountssolicited__c as aqb__estimatedaccountssolicited__c
,trim(aqb__event__c) as aqb__event__c
,trim(aqb__includeinannualfunddashboard__c) as aqb__includeinannualfunddashboard__c
,trim(aqb__institutionalunit__c) as aqb__institutionalunit__c
,trim(aqb__kpichart1__c) as aqb__kpichart1__c
,trim(aqb__kpichart2__c) as aqb__kpichart2__c
,trim(aqb__kpichart3__c) as aqb__kpichart3__c
,trim(aqb__kpichart4__c) as aqb__kpichart4__c
,trim(aqb__kpichartsize__c) as aqb__kpichartsize__c
,aqb__lengthindays__c as aqb__lengthindays__c
,trim(aqb__ownerunit__c) as aqb__ownerunit__c
,aqb__percentcomplete__c as aqb__percentcomplete__c
,aqb__percentofdayspast__c as aqb__percentofdayspast__c
,trim(aqb__preferencelisttype__c) as aqb__preferencelisttype__c
,aqb__responserategoal__c as aqb__responserategoal__c
,aqb__revg__c as aqb__revg__c
,aqb__startdate__c as aqb__startdate__c
,aqb__stopdate__c as aqb__stopdate__c
,trim(aqb__targetlisttype__c) as aqb__targetlisttype__c
,aqb__totalopenopportunities__c as aqb__totalopenopportunities__c
,aqb__countofaccountssolicited__c as aqb__countofaccountssolicited__c
,aqb__totalcampaignappealexpenses__c as aqb__totalcampaignappealexpenses__c
,trim(aqcv_conversionid__c) as aqcv_conversionid__c
,trim(aqc_campaign_appeal_code__c) as aqc_campaign_appeal_code__c
,trim(aqc_volunteer_contact_solicitor__c) as aqc_volunteer_contact_solicitor__c
,trim(vu_campaign_project_manager__c) as vu_campaign_project_manager__c
,display_on_preference_center__c as display_on_preference_center__c
,sort_order__c as sort_order__c
,matillion_batch_id as matillion_batch_id
,matillion_updated_timestamp as matillion_updated_timestamp
,'sfdc_aqb'  as source_name 
  from campaign
) 
select * from final 
